#!/usr/bin/dh-exec --with=subst
pyside2_install/py2*-relwithdebinfo/include/shiboken2 usr/include
pyside2_install/py2*-relwithdebinfo/lib/pkgconfig/shiboken2.pc usr/lib/${DEB_HOST_MULTIARCH}/pkgconfig
pyside2_install/py2*-relwithdebinfo/lib/libshiboken2*.so usr/lib/${DEB_HOST_MULTIARCH}
pyside3_install/py3*-relwithdebinfo/lib/libshiboken2*.so usr/lib/${DEB_HOST_MULTIARCH}
pyside2_install/py2*-relwithdebinfo/lib/cmake/Shiboken2* usr/lib/${DEB_HOST_MULTIARCH}/cmake
pyside3_install/py3*-relwithdebinfo/lib/cmake/Shiboken2*/Shiboken2Config.cpython* usr/lib/${DEB_HOST_MULTIARCH}/cmake/Shiboken2-${MAIN_VERSION_UPSTREAM}
